pragma Singleton
// Lumen Settings state. Settings runs as its OWN Quickshell process
// (shell/settings.qml) — crash-isolated, and using no memory while closed.
//   From the main shell: SettingsState.launch(page) starts it or, if it is
//   already running, switches its page and focuses it.
import QtQuick
import Quickshell
import Quickshell.Io
import qs.theme

Singleton {
    id: root
    property bool open: false
    property string page: Quickshell.env("LUMEN_SETTINGS_PAGE") || "appearance"

    readonly property var pages: [
        { id: "appearance",    icon: "palette",             label: "Appearance",          keys: "theme dark light accent colour transparency glass blur motion clock 12 24 icons sounds" },
        { id: "wallpaper",     icon: "wallpaper",           label: "Wallpaper",           keys: "background picture shuffle match accent" },
        { id: "bar",           icon: "top_panel_open",      label: "Bar & Island",        keys: "island date workspace hot corners" },
        { id: "windows",       icon: "select_window",       label: "Windows",             keys: "gaps corners rounding border animation speed focus follows mouse" },
        { id: "notifications", icon: "notifications",       label: "Notifications",       keys: "focus do not disturb dnd banners mute apps sound history" },
        { id: "network",       icon: "wifi",                label: "Network",             keys: "wifi wi-fi internet airplane vpn warp cloudflare dns" },
        { id: "bluetooth",     icon: "bluetooth",           label: "Bluetooth",           keys: "devices headphones pair connect battery" },
        { id: "sound",         icon: "volume_up",           label: "Sound",               keys: "volume output input microphone speaker headphones" },
        { id: "display",       icon: "brightness_6",        label: "Display",             keys: "brightness night light warmth" },
        { id: "lock",          icon: "lock",                label: "Lock screen",         keys: "widgets password unlock" },
        { id: "faceid",        icon: "face",                label: "Face ID",             keys: "face unlock gaze camera liveness anti photo calibrate strictness" },
        { id: "power",         icon: "battery_charging_80", label: "Power",               keys: "battery saver performance idle sleep suspend lock timeout screen off charge limit health" },
        { id: "ai",            icon: "auto_awesome",        label: "AI",                  keys: "assistant ask claude anthropic ollama local model api key chat" },
        { id: "keyboard",      icon: "keyboard",            label: "Keyboard & Gestures", keys: "shortcuts keybinds cheatsheet touchpad gestures corners" },
        { id: "about",         icon: "info",                label: "About",               keys: "version system hardware kernel hyprland" },
    ]
    property string search: ""
    readonly property var visiblePages: {
        const q = search.trim().toLowerCase();
        if (q === "") return pages;
        return pages.filter(p => (p.label + " " + p.keys).toLowerCase().includes(q));
    }

    function show(p) { if (p && pages.some(x => x.id === p)) page = p; open = true; }
    function toggle() { open = !open; }

    // One settings app per Hyprland session, found by its pid file — never
    // another session's (several Lumen sessions can run at once).
    readonly property string pidFile: (Quickshell.env("XDG_RUNTIME_DIR") || "/tmp") + "/lumen-settings-"
                                      + (Quickshell.env("HYPRLAND_INSTANCE_SIGNATURE") || "default") + ".pid"

    // Main shell → the settings app (reuse this session's, or start it)
    function launch(p) {
        Quickshell.execDetached(["sh", "-c",
            'pid=$(cat "$3" 2>/dev/null) && tr "\\0" " " < "/proc/$pid/cmdline" 2>/dev/null | grep -q settings.qml && ' +
            '{ qs ipc --pid "$pid" call settings open "$2" >/dev/null 2>&1; hyprctl dispatch "hl.dsp.focus({ window = \\"pid:$pid\\" })" >/dev/null 2>&1; exit 0; }; ' +
            'LUMEN_SETTINGS_PAGE="$2" exec qs -p "$1/shell/settings.qml"', "sh", Theme.lumenRoot, p || "appearance", pidFile]);
    }
    // Settings app → main shell (wallpaper picker, cheatsheet live there)
    function shellCall(target, fn) {
        Quickshell.execDetached([Theme.lumenRoot + "/bin/lumen-shell-ipc", target, fn]);
    }

    // Colour previews for theme/accent pickers (generated by theme/build.py)
    property var previews: ({ themes: [], accents: [] })
    FileView {
        path: Theme.lumenRoot + "/generated/previews.json"
        watchChanges: true
        onFileChanged: reload()
        onLoaded: { try { root.previews = JSON.parse(text()); } catch (e) {} }
    }

    function lumen(args) { Quickshell.execDetached([Theme.lumenRoot + "/bin/lumen"].concat(args)); }

}
