-- ─────────────────────────────────────────────────────────────────────────────
--  Lumen — Hyprland entry point (Lua config, Hyprland ≥ 0.56)
--  Only wires modules together. Launched by bin/lumen-session.
--  LM = the design tokens, generated by theme/build.py (`lumen theme` rebuilds).
-- ─────────────────────────────────────────────────────────────────────────────

local root = (os.getenv("LUMEN_ROOT") or (os.getenv("HOME") .. "/.config/lumen"))
LM = dofile(root .. "/generated/hypr/tokens.lua")
LUMEN_ROOT = root

require("environment")
require("monitors")
require("input")
require("look")
require("animations")
require("workspaces")
require("rules")
require("keybinds")
require("startup")

-- Machine-local overrides (untracked): ~/.config/lumen/local.lua
local f = io.open(root .. "/local.lua", "r")
if f then
    f:close()
    dofile(root .. "/local.lua")
end
