#!/usr/bin/env python3
"""Lumen token generator.

Reads theme/tokens.toml + theme/themes/<theme>.toml (+ the runtime state file
written by `lumen theme`), resolves every OKLCH color to sRGB hex, checks
contrast, and writes one output per consumer into generated/:

    generated/tokens.json        resolved tokens (read by Quickshell, scripts)
    generated/hypr/tokens.lua    Hyprland (Lua config) tokens
    generated/hypr/vars.conf     hyprlock $variables

Stdlib only. No network. Safe to run repeatedly (writes are atomic).
"""

from __future__ import annotations

import argparse
import json
import math
import os
import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
THEME_DIR = ROOT / "theme"
OUT = ROOT / "generated"
STATE = Path(os.environ.get("XDG_STATE_HOME", Path.home() / ".local/state")) / "lumen/state.json"

HEADER = "GENERATED by theme/build.py from theme/tokens.toml — do not edit by hand."


# ── color math ──────────────────────────────────────────────────────────────

def oklch_to_hex(L: float, C: float, H: float) -> str:
    """OKLCH → gamma-encoded sRGB hex (clipped to gamut)."""
    a, b = C * math.cos(math.radians(H)), C * math.sin(math.radians(H))
    l_ = L + 0.3963377774 * a + 0.2158037573 * b
    m_ = L - 0.1055613458 * a - 0.0638541728 * b
    s_ = L - 0.0894841775 * a - 1.2914855480 * b
    l, m, s = l_ ** 3, m_ ** 3, s_ ** 3
    lin = (
        4.0767416621 * l - 3.3077115913 * m + 0.2309699292 * s,
        -1.2684380046 * l + 2.6097574011 * m - 0.3413193965 * s,
        -0.0041960863 * l - 0.7034186147 * m + 1.7076147010 * s,
    )

    def enc(x: float) -> int:
        x = min(1.0, max(0.0, x))
        x = 12.92 * x if x <= 0.0031308 else 1.055 * x ** (1 / 2.4) - 0.055
        return round(x * 255)

    return "".join(f"{enc(v):02x}" for v in lin)


def luminance(hex6: str) -> float:
    def lin(c: int) -> float:
        c = c / 255
        return c / 12.92 if c <= 0.04045 else ((c + 0.055) / 1.055) ** 2.4

    r, g, b = (int(hex6[i:i + 2], 16) for i in (0, 2, 4))
    return 0.2126 * lin(r) + 0.7152 * lin(g) + 0.0722 * lin(b)


def contrast(a: str, b: str) -> float:
    hi, lo = sorted((luminance(a), luminance(b)), reverse=True)
    return (hi + 0.05) / (lo + 0.05)


def alpha_hex(a: float) -> str:
    return f"{round(min(1.0, max(0.0, a)) * 255):02x}"


# ── resolve ─────────────────────────────────────────────────────────────────

def load_state() -> dict:
    try:
        return json.loads(STATE.read_text())
    except (OSError, ValueError):
        return {}


def avoid_status_hues(h: float, theme: dict, margin: float = 25.0) -> float:
    """A wallpaper-derived accent must never be mistaken for success / warning /
    error (DESIGN.md §2.4): push it out of a ±margin band around each."""
    h %= 360
    for _ in range(3):
        for (_L, _C, sh) in theme["status"].values():
            d = (h - sh + 180) % 360 - 180
            if abs(d) < margin:
                h = (sh + (margin if d >= 0 else -margin)) % 360
    return h


def resolve(theme_name: str | None, accent_name: str | None, accent_hue: float | None) -> dict:
    tokens = tomllib.loads((THEME_DIR / "tokens.toml").read_text())
    state = load_state()

    theme_name = theme_name or state.get("theme") or tokens["active"]["theme"]
    accent_name = accent_name or state.get("accent") or tokens["active"]["accent"]
    theme_file = THEME_DIR / "themes" / f"{theme_name}.toml"
    if not theme_file.is_file():
        sys.exit(f"build.py: unknown theme '{theme_name}' (no {theme_file})")
    theme = tomllib.loads(theme_file.read_text())

    # Accent hue: explicit > wallpaper-sampled (state) > named preset.
    if accent_hue is None:
        if accent_name == "wallpaper":
            accent_hue = state.get("wallpaper_hue")
            try:
                accent_hue = avoid_status_hues(float(accent_hue), theme)
            except (TypeError, ValueError):
                accent_hue = tokens["accents"]["ion"]
        elif accent_name in tokens["accents"]:
            accent_hue = tokens["accents"][accent_name]
        else:
            sys.exit(f"build.py: unknown accent '{accent_name}'")

    nh = theme["neutral_hue"]
    colors = {k: oklch_to_hex(L, C, nh) for k, (L, C) in theme["neutral"].items()}
    acc = theme["accent"]
    colors["accent"] = oklch_to_hex(acc["l"], acc["c"], accent_hue)
    colors["accent_hover"] = oklch_to_hex(acc["l"] + acc["hover_dl"], acc["c"], accent_hue)
    colors["on_accent"] = oklch_to_hex(*acc["on_accent"], accent_hue)
    for k, (L, C, H) in theme["status"].items():
        colors[k] = oklch_to_hex(L, C, H)

    # Terminal palette: the 8 ANSI hues at one lightness/chroma so no colour
    # shouts; bright = +0.07 L. Background/foreground are the theme's own.
    dark = theme["mode"] == "dark"
    tL, tC = (0.74, 0.12) if dark else (0.50, 0.14)
    hues = {"red": 25, "green": 150, "yellow": 88, "blue": 250, "magenta": 330, "cyan": 200}
    term = {"black": colors["surface_elevated"] if dark else colors["text"],
            "white": colors["text_secondary"] if dark else colors["surface_hover"]}
    for k, h in hues.items():
        term[k] = oklch_to_hex(tL, tC, h)
        term["bright_" + k] = oklch_to_hex(tL + (0.07 if dark else -0.07), tC, h)
    term["bright_black"] = colors["text_muted"]
    term["bright_white"] = colors["text"]

    edge = theme["edge"]
    scale = theme["glass"]["alpha_scale"]
    glass = {k: min(1.0, v * scale) for k, v in tokens["glass"].items()}

    # Contrast gate: every text role must meet WCAG AA on surface.
    checks = {
        "text": 4.5, "text_secondary": 4.5, "text_muted": 4.5,
        "accent": 3.0, "error": 3.0, "success": 3.0, "warning": 3.0,
    }
    report = {k: round(contrast(colors[k], colors["surface"]), 2) for k in checks}
    report["on_accent"] = round(contrast(colors["on_accent"], colors["accent"]), 2)
    failures = [k for k, need in {**checks, "on_accent": 4.5}.items() if report[k] < need]

    # ── User preferences over the design tokens (Lumen Settings → Windows) ──
    window = dict(tokens["window"])
    radius = dict(tokens["radius"])
    motion = {**tokens["motion"], **({"reduced": state["reduced_motion"] == "on"} if "reduced_motion" in state else {})}
    gaps = {"compact": (2, 4), "normal": (4, 8), "roomy": (8, 16)}.get(state.get("gaps", ""))
    if gaps:
        window["gaps_in"], window["gaps_out"] = gaps
    corners = {"square": 0, "soft": 12, "round": 20}.get(state.get("corners", ""))
    if corners is not None:
        radius["md"] = corners
    border = {"off": 0, "thin": 1, "normal": 2}.get(state.get("border", ""))
    if border is not None:
        window["border"] = border
    speed = {"fast": 0.7, "normal": 1.0, "relaxed": 1.3}.get(state.get("anim_speed", ""), 1.0)
    for k in ("micro", "normal", "large", "window"):
        motion[k] = round(motion[k] * speed)
    window["follow_mouse"] = 0 if state.get("follow_mouse") == "off" else 1
    cursor = {"theme": state.get("cursor", "Bibata-Modern-Classic"), "size": int(state.get("cursor_size", 24))}

    return {
        "theme": theme_name,
        "mode": theme["mode"],
        "accent_name": accent_name,
        "accent_hue": accent_hue,
        "colors": colors,
        "edge": {"base": edge["base"], "border": edge["border"], "strong": edge["strong"]},
        "glass": glass,
        "type": tokens["type"],
        "space": tokens["space"],
        "radius": radius,
        "window": window,
        "motion": motion,
        "prefs": {k: state.get(k, d) for k, d in (("gaps", "normal"), ("corners", "soft"), ("border", "normal"),
                                                  ("anim_speed", "normal"), ("follow_mouse", "on"),
                                                  ("cursor", "Bibata-Modern-Classic"), ("cursor_size", "24"))},
        "idle": idle_prefs(state),
        "cursor": cursor,
        "blur": tokens["blur"],
        "shadow": tokens["shadow"],
        "island": tokens["island"],
        "locale": {**tokens.get("locale", {}), **({"clock": state["clock"]} if state.get("clock") in ("12h", "24h") else {})},
        "transparency": state.get("transparency", "on") != "off",
        "terminal": term,
        "contrast": report,
        "contrast_failures": failures,
    }


# ── emitters ────────────────────────────────────────────────────────────────

def emit_hypr(t: dict) -> str:
    c, m, e = t["colors"], t["motion"], t["edge"]
    reduced = m["reduced"]

    def dur(ms: float, exit_: bool = False) -> str:
        """Hyprland animation speed is in units of 100 ms."""
        if reduced:
            return "1"
        return f"{(ms * (m['exit_ratio'] if exit_ else 1)) / 100:.1f}"

    def op(v: float) -> float:
        return v if t["transparency"] else 1.0

    lines = [f"# {HEADER}", f"# theme={t['theme']} accent={t['accent_name']} (hue {t['accent_hue']})", ""]
    lines.append("# ── colors ──")
    for k, v in c.items():
        lines.append(f"$lm_{k} = rgb({v})")
    for k, v in c.items():   # bare hex, for Pango markup (hyprlock labels)
        lines.append(f"$lm_hex_{k} = {v}")
    g = t["glass"]
    lines.append(f"$lm_glass_chrome = rgba({c['surface']}{alpha_hex(g['chrome_alpha'])})")
    lines.append(f"$lm_glass_panel = rgba({c['surface']}{alpha_hex(g['panel_alpha'])})")
    lines.append(f"$lm_accent_border = rgba({c['accent']}{alpha_hex(0.85)})")
    lines.append(f"$lm_border = rgba({e['base']}{alpha_hex(e['border'])})")
    lines.append(f"$lm_border_strong = rgba({e['base']}{alpha_hex(e['strong'])})")
    lines.append(f"$lm_shadow = rgba(000000{alpha_hex(t['shadow']['alpha'])})")
    lines.append("")
    lines.append("# ── geometry ──")
    r, w = t["radius"], t["window"]
    lines += [
        f"$lm_radius_window = {r['md']}",
        f"$lm_squircle = {r['squircle']}",
        f"$lm_border_size = {w['border']}",
        f"$lm_follow_mouse = {w['follow_mouse']}",
        f"$lm_gaps_in = {w['gaps_in']}",
        f"$lm_gaps_out = {w['gaps_out']}",
        f"# window transparency: {'on' if t['transparency'] else 'OFF (lumen transparency on)'}",
        f"$lm_terminal_opacity = {op(w['terminal_opacity'])}",
        f"$lm_app_active = {op(w['app_active'])}",
        f"$lm_app_inactive = {op(w['app_inactive'])}",
        f"$lm_glass_app_active = {op(w['glass_app_active'])}",
        f"$lm_glass_app_inactive = {op(w['glass_app_inactive'])}",
        "",
        "# ── blur / shadow ──",
    ]
    for k, v in t["blur"].items():
        lines.append(f"$lm_blur_{k} = {v}")
    lines += [
        f"$lm_shadow_range = {t['shadow']['range']}",
        f"$lm_shadow_power = {t['shadow']['render_power']}",
        "",
        "# ── motion (Hyprland speed: 1 = 100 ms) ──",
        f"$lm_t_micro = {dur(m['micro'])}",
        f"$lm_t_normal = {dur(m['normal'])}",
        f"$lm_t_large = {dur(m['large'])}",
        f"$lm_t_window = {dur(m['window'])}",
        f"$lm_t_normal_exit = {dur(m['normal'], True)}",
        f"$lm_t_window_exit = {dur(m['window'], True)}",
        "",
        "# ── typography ──",
        f"$lm_font_ui = {t['type']['ui']}",
        f"$lm_font_mono = {t['type']['mono']}",
    ]
    return "\n".join(lines) + "\n"


def emit_hypr_lua(t: dict) -> str:
    """Tokens for the Lua Hyprland config (hypr/*.lua read them as LM)."""
    c, e, w, r, m = t["colors"], t["edge"], t["window"], t["radius"], t["motion"]
    op = (lambda v: v) if t["transparency"] else (lambda v: 1.0)

    def dur(ms, exit_=False):
        return 1 if m["reduced"] else round(ms * (m["exit_ratio"] if exit_ else 1) / 100, 2)

    def lua(v):
        if isinstance(v, bool):
            return "true" if v else "false"
        if isinstance(v, (int, float)):
            return repr(v)
        if isinstance(v, str):
            return '"' + v.replace('"', '\\"') + '"'
        if isinstance(v, (list, tuple)):
            return "{ " + ", ".join(lua(x) for x in v) + " }"
        if isinstance(v, dict):
            return "{ " + ", ".join(f"{k} = {lua(x)}" for k, x in v.items()) + " }"
        raise TypeError(v)

    tbl = {
        "theme": t["theme"], "accent_name": t["accent_name"],
        "color": {k: f"rgb({v})" for k, v in c.items()},
        "accent_border": f"rgba({c['accent']}{alpha_hex(0.85)})",
        "border": f"rgba({e['base']}{alpha_hex(e['border'])})",
        "shadow": f"rgba(000000{alpha_hex(t['shadow']['alpha'])})",
        "radius_window": r["md"], "squircle": r["squircle"],
        "border_size": w["border"], "gaps_in": w["gaps_in"], "gaps_out": w["gaps_out"],
        "follow_mouse": w["follow_mouse"],
        "cursor": t["cursor"]["theme"], "cursor_size": t["cursor"]["size"],
        "opacity": {"terminal": op(w["terminal_opacity"]), "app_active": op(w["app_active"]),
                    "app_inactive": op(w["app_inactive"]), "glass_active": op(w["glass_app_active"]),
                    "glass_inactive": op(w["glass_app_inactive"])},
        "blur": dict(t["blur"]),
        "shadow_range": t["shadow"]["range"], "shadow_power": t["shadow"]["render_power"],
        "t": {"micro": dur(m["micro"]), "normal": dur(m["normal"]), "large": dur(m["large"]),
              "window": dur(m["window"]), "normal_exit": dur(m["normal"], True), "window_exit": dur(m["window"], True)},
        "curves": {k: [[v[0], v[1]], [v[2], v[3]]] for k, v in m["curves"].items()},
    }
    return f"-- {HEADER}\nreturn {lua(tbl)}\n"


def emit_kitty(t: dict) -> str:
    c, term = t["colors"], t["terminal"]
    opacity = t["window"]["terminal_opacity"] if t["transparency"] else 1.0
    order = ["black", "red", "green", "yellow", "blue", "magenta", "cyan", "white"]
    lines = [f"# {HEADER}",
             f"background #{c['bg']}", f"foreground #{c['text']}",
             f"cursor #{c['accent']}", f"cursor_text_color #{c['on_accent']}",
             f"selection_background #{c['accent']}", f"selection_foreground #{c['on_accent']}",
             f"url_color #{c['accent']}",
             f"active_border_color #{c['accent']}", f"inactive_border_color #{c['surface_hover']}",
             f"active_tab_background #{c['surface_hover']}", f"active_tab_foreground #{c['text']}",
             f"inactive_tab_background #{c['bg']}", f"inactive_tab_foreground #{c['text_muted']}",
             f"tab_bar_background #{c['bg']}",
             f"mark1_background #{c['accent']}", f"mark1_foreground #{c['on_accent']}",
             f"background_opacity {opacity}"]
    for i, name in enumerate(order):
        lines.append(f"color{i} #{term[name]}")
        lines.append(f"color{i + 8} #{term['bright_' + name]}")
    return "\n".join(lines) + "\n"


def emit_starship(t: dict) -> str:
    c = t["colors"]
    return f"""# {HEADER}
# Lumen prompt: calm, one line, information only when it matters.
#   ~/Projects/lumen  main ●  2.3s  ❯
add_newline = false
format = "$directory$git_branch$git_status$python$nodejs$rust$cmd_duration$jobs$character"
palette = "lumen"

[palettes.lumen]
accent = "#{c['accent']}"
text = "#{c['text']}"
muted = "#{c['text_muted']}"
secondary = "#{c['text_secondary']}"
success = "#{c['success']}"
warning = "#{c['warning']}"
error = "#{c['error']}"

[directory]
style = "bold accent"
truncation_length = 3
truncation_symbol = "…/"
read_only = " 󰌾"
read_only_style = "muted"

[git_branch]
format = "[$symbol$branch]($style) "
symbol = " "
style = "secondary"

[git_status]
format = "([$all_status$ahead_behind]($style) )"
style = "warning"
conflicted = "="
modified = "●"
staged = "+"
untracked = "?"
deleted = "✕"
renamed = "»"
ahead = "↑$count"
behind = "↓$count"
diverged = "↕"
stashed = ""

[python]
format = "[$symbol$virtualenv]($style) "
symbol = " "
style = "muted"
detect_extensions = []
detect_files = []

[nodejs]
format = "[$symbol$version]($style) "
symbol = " "
style = "muted"

[rust]
format = "[$symbol$version]($style) "
symbol = " "
style = "muted"

[cmd_duration]
min_time = 2000
format = "[$duration]($style) "
style = "muted"

[jobs]
format = "[$symbol$number]($style) "
symbol = "✦"
style = "accent"

[character]
success_symbol = "[❯](accent)"
error_symbol = "[❯](error)"
vimcmd_symbol = "[❮](success)"
"""


IDLE_LOCK = {"2": 120, "5": 300, "10": 600, "15": 900, "30": 1800, "never": 0}
IDLE_SLEEP = {"15": 900, "30": 1800, "60": 3600, "battery": 900, "never": 0}


def idle_prefs(state: dict) -> dict:
    lock = state.get("idle_lock", "5")
    sleep = state.get("idle_sleep", "15")
    return {"lock": lock if lock in IDLE_LOCK else "5", "sleep": sleep if sleep in IDLE_SLEEP else "15"}


def emit_hypridle(state: dict) -> str:
    """hypridle.conf from Settings → Power → When idle.
    dim (1 min before the lock) → lock → screen off (30 s after) → suspend."""
    p = idle_prefs(state)
    lock, sleep = IDLE_LOCK[p["lock"]], IDLE_SLEEP[p["sleep"]]
    ipc = "~/.config/lumen/bin/lumen-shell-ipc"
    dpms = "hyprctl dispatch 'hl.dsp.dpms(\"%s\")'"
    out = [f"# {HEADER}", f"# lock: {p['lock']} · sleep: {p['sleep']}  (lumen set idle_lock|idle_sleep …)", "",
           "general {",
           "    # The Lumen shell draws the lock; hyprlock is the fallback if the shell isn't running",
           f"    lock_cmd = {ipc} lock lock || pidof hyprlock || hyprlock -c ~/.config/lumen/hypr/hyprlock.conf",
           "    before_sleep_cmd = loginctl lock-session",
           "    # Screen on, then let Face ID look straight away (you just opened the lid)",
           f"    after_sleep_cmd = {dpms % 'on'}; {ipc} lock wake",
           "    ignore_dbus_inhibit = false",
           "    # Hold suspend until the lock screen is really up (ext-session-lock confirmed),",
           "    # so waking never flashes the desktop.",
           "    inhibit_sleep = 3",
           "}"]

    def listener(timeout: int, on: str, resume: str | None = None) -> None:
        out.extend(["", "listener {", f"    timeout = {timeout}", f"    on-timeout = {on}"]
                   + ([f"    on-resume = {resume}"] if resume else []) + ["}"])

    idle = "~/.config/lumen/scripts/idle.sh"   # skips every step while this session isn't on screen
    if lock:
        listener(max(30, lock - 60), f"{idle} dim", f"{idle} undim")
        listener(lock, f"{idle} lock")
        listener(lock + 30, f"{idle} screen-off", f"{idle} screen-on")
    if sleep:
        listener(max(sleep, lock + 60), f"{idle} suspend" + (" --battery-only" if p["sleep"] == "battery" else ""))
    return "\n".join(out) + "\n"


def emit_qt6ct(t: dict) -> tuple[str, str]:
    """qt6ct palette + config (used only when qt6ct is installed; lumen-session
    switches QT_QPA_PLATFORMTHEME for the Lumen session alone)."""
    c = {k: "#" + v for k, v in t["colors"].items()}
    dark = t["mode"] != "light"
    # QPalette roles, in order: WindowText Button Light Midlight Dark Mid Text
    # BrightText ButtonText Base Window Shadow Highlight HighlightedText Link
    # LinkVisited AlternateBase NoRole ToolTipBase ToolTipText PlaceholderText Accent
    def row(text, muted=False):
        fg = c["text_muted"] if muted else text
        return ", ".join([fg, c["surface_elevated"], c["surface_hover"], c["surface_elevated"],
                          "#000000" if dark else c["text_muted"], c["surface"], fg, "#ffffff",
                          fg, c["surface"], c["bg"], "#000000", c["accent"], c["on_accent"],
                          c["accent"], c["accent_hover"], c["surface_elevated"], c["bg"],
                          c["surface_elevated"], c["text"], c["text_muted"], c["accent"]])
    scheme = "\n".join([f"# {HEADER}", "[ColorScheme]",
                        f"active_colors={row(c['text'])}",
                        f"disabled_colors={row(c['text'], muted=True)}",
                        f"inactive_colors={row(c['text'])}", ""])
    ui, mono = t["type"]["ui"], t["type"]["mono"]
    conf = "\n".join([f"# {HEADER}", "[Appearance]",
                      f"color_scheme_path={OUT / 'qt6ct/colors/lumen.conf'}",
                      "custom_palette=true", "style=Breeze", "icon_theme=breeze-dark" if dark else "icon_theme=breeze",
                      "standard_dialogs=default", "",
                      "[Fonts]",
                      f'fixed="{mono},10,-1,5,400,0,0,0,0,0,0,0,0,0,0,1"',
                      f'general="{ui},10,-1,5,400,0,0,0,0,0,0,0,0,0,0,1"', ""])
    return scheme, conf


def emit_previews(t: dict) -> str:
    """Colour previews for Lumen Settings: every theme (with the active accent)
    and every accent (in the active theme)."""
    tokens = tomllib.loads((THEME_DIR / "tokens.toml").read_text())
    themes = []
    for f in sorted((THEME_DIR / "themes").glob("*.toml")):
        th = tomllib.loads(f.read_text())
        nh, n, a = th["neutral_hue"], th["neutral"], th["accent"]
        themes.append({
            "id": f.stem, "name": th["name"], "mode": th["mode"],
            "bg": oklch_to_hex(*n["bg"], nh), "surface": oklch_to_hex(*n["surface"], nh),
            "elevated": oklch_to_hex(*n["surface_elevated"], nh), "text": oklch_to_hex(*n["text"], nh),
            "muted": oklch_to_hex(*n["text_muted"], nh),
            "accent": oklch_to_hex(a["l"], a["c"], t["accent_hue"]),
        })
    cur = tomllib.loads((THEME_DIR / "themes" / f"{t['theme']}.toml").read_text())["accent"]
    accents = [{"id": k, "hex": oklch_to_hex(cur["l"], cur["c"], h)} for k, h in tokens["accents"].items()]
    return json.dumps({"themes": themes, "accents": accents}, indent=1) + "\n"


def write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(text)
    tmp.replace(path)


def main() -> int:
    ap = argparse.ArgumentParser(description="Generate Lumen theme outputs from tokens.")
    ap.add_argument("--theme")
    ap.add_argument("--accent")
    ap.add_argument("--accent-hue", type=float)
    ap.add_argument("--check", action="store_true", help="print contrast report, write nothing")
    args = ap.parse_args()

    t = resolve(args.theme, args.accent, args.accent_hue)
    if args.check:
        print(json.dumps({"theme": t["theme"], "accent": t["accent_name"], "contrast": t["contrast"],
                          "failures": t["contrast_failures"]}, indent=2))
        return 1 if t["contrast_failures"] else 0

    if t["contrast_failures"]:
        print(f"build.py: WARNING contrast below target for {t['contrast_failures']}", file=sys.stderr)

    write(OUT / "tokens.json", json.dumps(t, indent=2) + "\n")
    write(OUT / "hypr/vars.conf", emit_hypr(t))            # hyprlock (hyprlang) — fallback lock
    write(OUT / "hypr/tokens.lua", emit_hypr_lua(t))       # hyprland.lua (Hyprland's config is Lua)
    write(OUT / "kitty/theme.conf", emit_kitty(t))
    write(OUT / "starship.toml", emit_starship(t))
    write(OUT / "previews.json", emit_previews(t))
    write(OUT / "hypr/hypridle.conf", emit_hypridle(load_state()))
    qt_scheme, qt_conf = emit_qt6ct(t)
    write(OUT / "qt6ct/colors/lumen.conf", qt_scheme)
    write(OUT / "qt6ct/qt6ct.conf", qt_conf)
    print(f"lumen: generated theme={t['theme']} accent={t['accent_name']} → {OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
