#!/bin/sh
# recovery.sh — Lumen Recovery. Works from a bare TTY (no graphics needed):
#   lumen recovery                   an interactive menu
# and from Settings → Backup & recovery through these commands:
#   recovery.sh config-backup [--auto]   save Lumen's settings (--auto: at most once a day)
#   recovery.sh config-list              JSON: [{file, time, size, commit}] newest first
#   recovery.sh config-restore <file>    restore one (your current settings are saved first)
#   recovery.sh safe on|off|status       next login starts without the Lumen shell (safe mode)
#   recovery.sh safe-session             start a minimal Hyprland now (from a TTY), not Lumen's config
#   recovery.sh reset-theme              move generated/ aside and rebuild it
#   recovery.sh git-status               the repository's state
#   recovery.sh git-stash                put local changes aside (git stash; nothing is lost)
#   recovery.sh git-branch <commit>      check out an earlier version on a new branch recovery-<date>
# Nothing here deletes: backups over the limit of 20 go to the trash, and
# everything replaced is moved aside or saved first.
set -u
LUMEN_ROOT=${LUMEN_ROOT:-$HOME/.config/lumen}
STATE_DIR=${XDG_STATE_HOME:-$HOME/.local/state}/lumen
BK_DIR=${XDG_DATA_HOME:-$HOME/.local/share}/lumen/config-backups
KEEP=20
DOCTOR=$LUMEN_ROOT/scripts/doctor.sh

config_backup() {   # [--auto]
    mkdir -p "$BK_DIR"
    if [ "${1:-}" = --auto ] && ls "$BK_DIR"/lumen-config-"$(date +%Y-%m-%d)"_*.tar.gz >/dev/null 2>&1; then return 0; fi
    stage=$(mktemp -d) || return 1
    mkdir -p "$stage/state" "$stage/repo"
    [ -d "$STATE_DIR" ] && cp -a "$STATE_DIR/." "$stage/state/" 2>/dev/null
    rm -f "$stage/state/"*.lock "$stage/state/"*.tmp 2>/dev/null
    for f in local.lua local.conf session.env; do [ -f "$LUMEN_ROOT/$f" ] && cp -a "$LUMEN_ROOT/$f" "$stage/repo/"; done
    {
        echo "time=$(date +%s)"
        echo "host=$(hostname 2>/dev/null)"
        echo "commit=$(git -C "$LUMEN_ROOT" describe --always --dirty --tags 2>/dev/null || echo unknown)"
    } > "$stage/meta"
    base="$BK_DIR/lumen-config-$(date +%Y-%m-%d_%H%M%S)"; out="$base.tar.gz"; n=1
    while [ -e "$out" ]; do out="$base-$n.tar.gz"; n=$((n + 1)); done
    tar -czf "$out" -C "$stage" . && rm -rf "$stage"
    chmod 600 "$out"
    # Over the limit: the oldest go to the trash (never deleted outright)
    if command -v gio >/dev/null; then
        # shellcheck disable=SC2012  # our own file names, no odd characters
        ls -1 "$BK_DIR"/lumen-config-*.tar.gz 2>/dev/null | sort | head -n -"$KEEP" | while IFS= read -r old; do gio trash -- "$old"; done
    fi
    echo "$out"
}

config_list() {
    # shellcheck disable=SC2012
    ls -1 "$BK_DIR"/lumen-config-*.tar.gz 2>/dev/null | sort -r | while IFS= read -r f; do
        meta=$(tar -xzOf "$f" ./meta 2>/dev/null)
        t=$(printf '%s\n' "$meta" | sed -n 's/^time=//p'); c=$(printf '%s\n' "$meta" | sed -n 's/^commit=//p')
        jq -cn --arg f "$f" --arg t "${t:-0}" --arg c "$c" --arg s "$(stat -c %s "$f")" '{file:$f, time:($t|tonumber), commit:$c, size:($s|tonumber)}'
    done | jq -sc .
}

config_restore() {
    f=${1:?}
    case $f in "$BK_DIR"/lumen-config-*.tar.gz) ;; *) echo "Not a Lumen config backup: $f" >&2; return 1 ;; esac
    [ -f "$f" ] || { echo "No such backup." >&2; return 1; }
    # Read the chosen backup first, then save the current settings, then restore
    stage=$(mktemp -d) || return 1
    tar -xzf "$f" -C "$stage" && [ -f "$stage/meta" ] || { rm -rf "$stage"; echo "Couldn't read the backup." >&2; return 1; }
    before=$(config_backup) || { rm -rf "$stage"; return 1; }
    mkdir -p "$STATE_DIR"
    cp -a "$stage/state/." "$STATE_DIR/"
    for x in "$stage"/repo/*; do [ -f "$x" ] && cp -a "$x" "$LUMEN_ROOT/"; done
    rm -rf "$stage"
    python3 "$LUMEN_ROOT/theme/build.py" >/dev/null 2>&1
    echo "restored (your previous settings were saved as $(basename "$before"))"
}

safe() {
    case ${1:-status} in
    on)  mkdir -p "$STATE_DIR"; date > "$STATE_DIR/safe-mode"; echo on ;;
    off) [ -e "$STATE_DIR/safe-mode" ] && mv -- "$STATE_DIR/safe-mode" "$STATE_DIR/safe-mode.off"; echo off ;;
    *)   [ -e "$STATE_DIR/safe-mode" ] && echo on || echo off ;;
    esac
}

# A minimal Hyprland: a terminal, close, exit. Nothing of Lumen's config runs.
safe_session() {
    dir=${XDG_RUNTIME_DIR:-/tmp}/lumen-safe; mkdir -p "$dir"
    cat > "$dir/hyprland.lua" <<EOF
-- Lumen safe session (generated by scripts/recovery.sh): only the essentials.
hl.bind("SUPER + Return", hl.dsp.exec_cmd("kitty"))
hl.bind("SUPER + Q", hl.dsp.window.close())
hl.bind("SUPER + SHIFT + E", hl.dsp.exit())
hl.bind("CTRL + ALT + SHIFT + SUPER + Escape", hl.dsp.exit())
hl.on("hyprland.start", function()
    hl.exec_cmd("kitty --title 'Lumen Recovery' sh -c 'echo Lumen safe session: Super+Enter terminal, Super+Q close, Super+Shift+E exit.; echo; exec $LUMEN_ROOT/bin/lumen recovery'")
end)
EOF
    if [ -n "${WAYLAND_DISPLAY:-}" ]; then echo "Already in a graphical session; log out to a TTY first." >&2; return 1; fi
    if command -v start-hyprland >/dev/null; then exec start-hyprland -- -c "$dir/hyprland.lua"; fi
    exec Hyprland -c "$dir/hyprland.lua"
}

reset_theme() {
    g=$LUMEN_ROOT/generated
    [ -d "$g" ] && mv -- "$g" "$g.bak-$(date +%Y%m%d-%H%M%S)"
    python3 "$LUMEN_ROOT/theme/build.py" && echo "rebuilt (the old one was moved aside to generated.bak-…)"
}

git_status() {
    git -C "$LUMEN_ROOT" rev-parse --git-dir >/dev/null 2>&1 || { echo "Lumen's folder isn't a git checkout."; return 0; }
    git -C "$LUMEN_ROOT" log --oneline -n 1
    git -C "$LUMEN_ROOT" status --short --branch
}
git_stash() {
    if git -C "$LUMEN_ROOT" diff --quiet && git -C "$LUMEN_ROOT" diff --cached --quiet; then echo "No local changes."; return 0; fi
    git -C "$LUMEN_ROOT" stash push -m "lumen recovery $(date '+%Y-%m-%d %H:%M')" && echo "Local changes put aside — git stash pop brings them back."
}
git_branch() {
    c=${1:?}
    git -C "$LUMEN_ROOT" rev-parse --verify -q "$c^{commit}" >/dev/null || { echo "No such commit: $c" >&2; return 1; }
    git -C "$LUMEN_ROOT" diff --quiet && git -C "$LUMEN_ROOT" diff --cached --quiet || git_stash
    b="recovery-$(date +%Y%m%d-%H%M)"
    git -C "$LUMEN_ROOT" switch -c "$b" "$c" && echo "Now on $b. Go back with: git -C $LUMEN_ROOT switch -"
}

confirm() { printf '%s [y/N] ' "$1"; read -r a; case $a in y|Y|yes) return 0 ;; esac; return 1; }
pause() { printf '\nPress Enter to go back. '; read -r _; }
viewer() { if command -v less >/dev/null; then less -R "$1"; else cat "$1"; pause; fi; }

menu() {
    while :; do
        clear 2>/dev/null
        cat <<EOF
  Lumen Recovery
  ──────────────
  1  Health check
  2  Back up Lumen's settings now
  3  Restore settings from a backup
  4  Safe mode at next login (no shell)       [now: $(safe status)]
  5  Start a minimal Hyprland session now (from a TTY)
  6  Reset the generated theme
  7  Lumen's code: status / put changes aside / go to an earlier version
  8  Logs: startup · shell · journal
  q  Quit
EOF
        printf '\n  Choose: '; read -r c
        case $c in
        1) "$DOCTOR" check | jq -r '.[] | "  \(if .state == "ok" then "✓" elif .state == "warn" then "!" else "✗" end) \(.title): \(.detail)"'; pause ;;
        2) f=$(config_backup) && echo "  Saved $f"; pause ;;
        3) config_list | jq -r 'to_entries[] | "  \(.key + 1)  \(.value.time | strftime("%Y-%m-%d %H:%M"))  \(.value.commit)"'
           printf '\n  Number to restore (Enter to cancel): '; read -r n
           case $n in ''|*[!0-9]*) ;; *)
               f=$(config_list | jq -r --argjson n "$n" '.[$n - 1].file // empty')
               [ -n "$f" ] && confirm "  Restore $(basename "$f")? Your current settings are saved first." && config_restore "$f" ;;
           esac; pause ;;
        4) if [ "$(safe status)" = on ]; then safe off >/dev/null; echo "  Safe mode off."
           else safe on >/dev/null; echo "  The next login starts Hyprland without the Lumen shell (once)."; fi; pause ;;
        5) confirm "  Start a minimal Hyprland session?" && safe_session; pause ;;
        6) confirm "  Move generated/ aside and rebuild it?" && reset_theme; pause ;;
        7) git_status; echo
           echo "  a  Put local changes aside (git stash)"
           echo "  b  Go to an earlier version (on a new branch)"
           printf '  Choose (Enter to go back): '; read -r g
           case $g in
           a) confirm "  Stash local changes?" && git_stash ;;
           b) git -C "$LUMEN_ROOT" log --oneline -n 15 | sed 's/^/  /'
              printf '  Commit: '; read -r cm
              [ -n "$cm" ] && confirm "  Check out $cm on a new branch?" && git_branch "$cm" ;;
           esac; pause ;;
        8) echo "  a  Startup log   b  Shell log   c  Journal"; printf '  Choose: '; read -r l
           rd=${XDG_RUNTIME_DIR:-/tmp}
           case $l in
           a) viewer "$rd/lumen-startup.log" ;;
           b) "$DOCTOR" shell-log "$rd/lumen-shell-log.log"; viewer "$rd/lumen-shell-log.log" ;;
           c) "$DOCTOR" journal "$rd/lumen-journal.log"; viewer "$rd/lumen-journal.log" ;;
           esac ;;
        q|Q|'') exit 0 ;;
        esac
    done
}

case ${1:-menu} in
menu) menu ;;
config-backup) config_backup "${2:-}" ;;
config-list) config_list ;;
config-restore) config_restore "${2:-}" ;;
safe) safe "${2:-status}" ;;
safe-session) safe_session ;;
reset-theme) reset_theme ;;
git-status) git_status ;;
git-stash) git_stash ;;
git-branch) git_branch "${2:-}" ;;
*) sed -n '2,15p' "$0" | sed 's/^# \{0,1\}//' >&2; exit 2 ;;
esac
